fake-dummy:
  module: dummy
  module-name: real-dummy
  version: "0.1.0"
  author: Nobody
  author-email: nobody@foo.com
  maintainer: Another
  maintainer-email: another@bar.com
  url: https://github.com/nobody/dummy
---
author-fake-dummy:
  module: dummy
  module-name: real-dummy
  version: "1.0.0"
  author: Somebody
  author-email: somebody@foo.com
  maintainer: Anyone
  maintainer-email: anyone@bar.com
  url: https://github.com/somebody/dummy
